import LegalLayout from "../components/LegalLayout";

export default function Terms() {
  return (
    <LegalLayout
      title="Terms of Use — SocialToolkit"
      description="Terms of Use for SocialToolkit — rules and conditions for using our free AI tools."
      pageTag="Legal"
      updated="January 1, 2026"
    >
      <div className="highlight">
        <p>Please read these Terms of Use carefully before using SocialToolkit. By accessing or using our website, you agree to be bound by these terms. If you do not agree, please do not use our website.</p>
      </div>

      <h2>1. Acceptance of terms</h2>
      <p>By using SocialToolkit (&quot;the website&quot;, &quot;our service&quot;), you confirm that you are at least 13 years of age and agree to these Terms of Use and our <a href="/privacy">Privacy Policy</a>. These terms apply to all visitors and users of the website.</p>

      <h2>2. Description of service</h2>
      <p>SocialToolkit provides free AI-powered tools for content creators, including:</p>
      <ul>
        <li>Hashtag Generator — generates relevant hashtags for social media posts</li>
        <li>Caption Writer — creates captions for social media content</li>
        <li>Bio Maker — generates profile bios for social media platforms</li>
        <li>Video Idea Generator — suggests content ideas for video creators</li>
      </ul>
      <p>These tools are provided free of charge and are supported by advertising.</p>

      <h2>3. Acceptable use</h2>
      <p>You agree to use SocialToolkit only for lawful purposes. You must not use our service to:</p>
      <ul>
        <li>Generate content that is illegal, harmful, threatening, abusive, or offensive</li>
        <li>Generate spam, misleading content, or content that violates platform terms of service</li>
        <li>Attempt to interfere with or disrupt our website or servers</li>
        <li>Use automated tools to make excessive requests to our service</li>
        <li>Collect or harvest any information from our website without permission</li>
        <li>Impersonate any person or entity</li>
      </ul>

      <h2>4. AI-generated content</h2>
      <p>Our tools use artificial intelligence to generate content suggestions. You acknowledge that:</p>
      <ul>
        <li>AI-generated content may not always be accurate, appropriate, or suitable for your needs</li>
        <li>You are solely responsible for reviewing and using any content generated by our tools</li>
        <li>We do not guarantee that AI-generated content will achieve any particular result on social media</li>
        <li>You retain full responsibility for any content you publish using suggestions from our tools</li>
      </ul>

      <h2>5. Intellectual property</h2>
      <p>The SocialToolkit website, including its design, logo, code, and content, is owned by SocialToolkit and protected by intellectual property laws. You may not copy, reproduce, or distribute our website content without permission.</p>
      <p>Content generated by our AI tools based on your input is provided for your personal use. We do not claim ownership of content you generate using our tools.</p>

      <h2>6. Advertising</h2>
      <p>Our website displays advertisements through Google AdSense. These ads are provided by Google and its advertising partners. We are not responsible for the content of advertisements displayed on our site. By using our website, you consent to the display of advertisements.</p>

      <h2>7. Disclaimer of warranties</h2>
      <p>SocialToolkit is provided &quot;as is&quot; and &quot;as available&quot; without any warranties of any kind, either express or implied. We do not warrant that:</p>
      <ul>
        <li>The service will be uninterrupted, error-free, or available at all times</li>
        <li>The AI-generated content will be accurate, complete, or suitable for any purpose</li>
        <li>The service will meet your specific requirements or expectations</li>
      </ul>

      <h2>8. Limitation of liability</h2>
      <p>To the maximum extent permitted by law, SocialToolkit and its operators shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of our website or the content generated by our tools. Our total liability shall not exceed the amount you paid to use our service (which is zero, as our service is free).</p>

      <h2>9. Third-party links and services</h2>
      <p>Our website may contain links to third-party websites. We are not responsible for the content, privacy practices, or terms of those websites. Links do not constitute endorsement of those sites.</p>

      <h2>10. Changes to the service</h2>
      <p>We reserve the right to modify, suspend, or discontinue any part of our service at any time without notice. We are not liable to you or any third party for any modification, suspension, or discontinuation of the service.</p>

      <h2>11. Changes to these terms</h2>
      <p>We may update these Terms of Use at any time. Changes will be effective when posted on this page with an updated date. Your continued use of our website after changes are posted means you accept the updated terms.</p>

      <h2>12. Governing law</h2>
      <p>These Terms of Use are governed by and construed in accordance with applicable laws. Any disputes arising from these terms shall be resolved through good-faith negotiation.</p>

      <h2>13. Contact us</h2>
      <p>If you have any questions about these Terms of Use, please contact us:</p>
      <ul>
        <li>Email: <a href="mailto:socialaikit@gmail.com">socialaikit@gmail.com</a></li>
        <li>Website: <a href="/contact">Contact page</a></li>
      </ul>
    </LegalLayout>
  );
}
